### ISSUE TITLE
Improper sentence on MockMvc

### ISSUE THREAD

**Issue by alb-i986** [spring-guides/gs-spring-boot#118]
> MockMvc comes from Spring Test and lets you, through a set of convenient builder classes, **send HTTP requests** into the DispatcherServlet and make assertions about the result

https://github.com/spring-guides/gs-spring-boot/blob/main/README.adoc#add-unit-tests

If I'm not mistaken (I'm still learning Spring), when `MockMvc` is used, there's no real (local) web environment initialized, `MockMvc` is a pure in-memory implementation of Spring's web environment machinery.
Therefore I would argue that it's improper to state that:

> MockMvc lets you send HTTP requests

Instead, I would suggest something along the lines of:

> MockMvc lets you send HTTP requests (though it doesn't _actually_ send real HTTP requests because it's a pure in-memory HTTP server implementation)

Thanks

**Comment by Buzzardo** [comment]
I disagree. An HTTP request can go to a local destination, including from one in-memory location to another in-memory location). The fact that it's all in-memory doesn't invalidate the notion of sending an HTTP request.
