### ISSUE TITLE
Update Spring Boot to the latest version

### ISSUE THREAD

**Issue by robertmcnees** [spring-guides/gs-spring-boot#166]
Update the guide to use the most recent Spring Boot version.

Files that require changes are:

```
initial/build.gradle
initial/pom.xml
complete/build.gradle
complete/pom.xml
```

**Comment by bodote** [comment]
i have opened the [pull request](https://github.com/spring-guides/gs-spring-boot/pull/167)

**Comment by robertmcnees** [comment]
This project now manages dependency upgrades with dependabot. Closing this issue.
