### ISSUE TITLE
Remove unused CI files

### ISSUE THREAD

**Issue by robertmcnees** [spring-guides/gs-spring-boot#174]
The file `test/run.sh` is no longer required. This file and the `test` directory can be deleted.

The file was originally used for Jenkins CI. Now that this project has been converted to GitHub Actions, this file can be removed.

**Comment by Aysha-py** [comment]
Hi @robertmcnees , I will create a PR for this issue, I have worked on something similar.

**Comment by robertmcnees** [comment]
Fixed with PR #175. Closing issue. Thanks for the PR!

**Comment by Aysha-py** [comment]
Hi @robertmcnees , thanks for merging my PR.

i’d like to know if there is a community for contributors, if there is one, I’d lover to join the community.

Thanks

**Comment by robertmcnees** [comment]
Hi @Aysha-py. Spring is always open to community contributions! Thank you again for the PR.

I don't have an all inclusive list of Spring communities, but I'd recommend checking out Spring Users on LinkedIn. There are 162,000 members. I'd also recommend checking out [Spring Office Hours](https://www.springofficehours.io/). Two of our developer advocates regularly run a podcast focused on the community. I'm sure there are others.

If you are looking to get more involved in OSS contributions, pick the project that you are most passionate about and check out the public issues. Sometimes you will find issues tagged with 'good first issue' or something similar. All issues vary in complexity, so try to find one at the appropriate level to what you're aiming for.

I'm using the `spring-guides` org to offer a first step to the OSS process. If you are looking for additional opportunities to contribute here, you could update our guides to the latest patch versions. This repository is a good example. The Dependabot configuration [excludes patch versions](https://github.com/spring-guides/gs-spring-boot/blob/f7021a776f0b4dcd1a50f95f07c7d79754966f11/.github/dependabot.yml#L8), in an effort to reduce the maintenance burden. However, if someone submitted a PR to update the patch version we would have a look. Spring Boot usually [releases](https://calendar.spring.io/) patch versions every month. Right now this guide is on 3.3.0 and it will stay there until Dependabot finds 3.4.0 and submits an automated PR in November. Until then, someone could manually update to 3.3.1 now, 3.3.2 next month, etc. This is a change that could be made in any of our guides.
