### ISSUE TITLE
HelloControllerIT.java not appearing properly on the website

### ISSUE THREAD

**Issue by SuleymanSchedules** [spring-guides/gs-spring-boot#177]
![image](https://github.com/user-attachments/assets/48ec4240-75e2-4108-af84-5a22e04a9ef9)

As you can see, the test isn't showing up as it's supposed to. The rest of the code on the page appears fine though

**Comment by Buzzardo** [comment]
A previous commit renamed that file. I made the name match in the readme, so it works correctly now.
