### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by SuleymanSchedules** [spring-guides/gs-spring-boot#178]
![image](https://github.com/user-attachments/assets/bd8fab78-a43b-47a9-be8c-42e9d9947e8d)

The link to the actuator model is dead and needs replacing. This is what's currently linked: http://docs.spring.io/spring-boot/docs/3.3.0/reference/htmlsingle/#actuator

**Comment by SuleymanSchedules** [comment]
Not the only one. There's many dead links following this one.

**Comment by Buzzardo** [comment]
Due to a recent change in the URL structure of Boot's docs, the `spring_boot_version` attribute needs to be `current` rather than a specific version. I made that change, which should fix this issue (it did in my local test). If it pops up again, please open a new issue for it. Thanks.
