### ISSUE TITLE
Build with Maven: section is empty

### ISSUE THREAD

**Issue by php-coder** [spring-guides/gs-spring-boot#28]
I've found out that section `Build with Maven` in [this tutorial](https://spring.io/guides/gs/spring-boot/) is empty. The same problem with neighbor sections about Gradle/IDE. I'm using Firefox 46.0.1 if it matters.

**Comment by dsyer** [comment]
Works for me. Try another browser? (You have to click on the arrow to the left to unfold the folded sections, remember.)

**Comment by php-coder** [comment]
>Works for me. Try another browser?

:-|

> (You have to click on the arrow to the left to unfold the folded sections, remember.)

It doesn't matter where I'm clicking.

I'm inspecting `<div>` and they're empty. In the developer's console I see a warning when loading `https://spring.io/5f6257c/app/main.js`: `mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create`.

**Comment by gregturn** [comment]
@php-coder In your browser, are you able to clear local storage for the site? The toggle option stores a tiny bit of text to remember your choice.

**Comment by php-coder** [comment]
Hm.. works for me on Firefox 47 and Safari under Mac.

>@php-coder In your browser, are you able to clear local storage for the site?

@gregturn I'll try it tomorrow.

**Comment by php-coder** [comment]
@gregturn local storage is empty.

**Comment by php-coder** [comment]
P.S. @gregturn but after executing `localStorage.clear()` in the WebConsole it works!
