### ISSUE TITLE
Tag/Version the repo

### ISSUE THREAD

**Issue by rishabhtulsian** [spring-guides/gs-spring-boot#29]
Hi, I would love it if you could tag/version the repo when you update it to a new spring boot version. So that I can easily get the code working with a specific spring boot version (for example: v1.3.7 commit ce568f8)

**Comment by gregturn** [comment]
Hmm. Ive never thought of that. I can checkout if the mr tool supports tagging. If so, it wouldn't be hard going forward.

**Comment by gregturn** [comment]
Okay, I've taken your suggestion under advisement, and from this point forward, will tag all the guides when the version gets bumped.
