### ISSUE TITLE
Missing ./gradlew

### ISSUE THREAD

**Issue by jest** [spring-guides/gs-spring-boot#33]
When following the guide with Gradle build path from scratch, the following command

```
./gradlew build && java -jar build/libs/gs-spring-boot-0.1.0.jar
```

cannot be performed, as there is no `gradlew` — it hasn't been created anywhere previously. So either create one with `gradle wrapper`, or change `./gradlew` with `gradle` in that line.

**Comment by dsyer** [comment]
It's here: https://github.com/spring-guides/gs-spring-boot/blob/master/complete/gradlew.

**Comment by jest** [comment]
I know where it is. :) But when you follow the Getting Started on the web (https://spring.io/guides/gs/spring-boot/) there's no `gradlew`, because you never clone the repo.
