### ISSUE TITLE
Not able to run spring boot app with provided complete/build.gradle

### ISSUE THREAD

**Issue by hari-rayapaneni** [spring-guides/gs-spring-boot#39]
I'm using STS IDE, when I use your gradle file its not downloading the jars.

How I build my Project:
clean build

I'm new to Spring boot please help me to get what are all the basic dependencies for a Spring boot App

**Comment by dsyer** [comment]
There are clear instructions for how to build and run the project from the command line in the guide. There is also a "Build with your IDE" section with links to IDEs including STS. Is part of that still unclear?
