### ISSUE TITLE
Not ready for non-English users

### ISSUE THREAD

**Issue by paulvi** [spring-guides/gs-spring-boot#7]
Thank you for great work on guides.

Most of guides build do not have source encoding set:

for maven

    <properties>
        
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    </properties>

and for gradle

`[ compileJava, compileTestJava ]*.options*.encoding = 'UTF-8'`

http://www.romseysoftware.co.uk/2012/03/12/gradle-and-utf-8/

**Comment by dsyer** [comment]
It looks to me like that change was merged in 1.1.x somewhere, so this is now working in Maven and Gradle.
