### ISSUE TITLE
problems with spring boot project using gradle

### ISSUE THREAD

**Issue by lonely917** [spring-guides/gs-spring-boot#77]
I use intelliJ to create springboot project，the created project run with no problems when i choose build with maven.  If i choose build with gradle, the created project can run , but the following problems occur:
1. application.properties where i change the http port seems doesn't work (\spring\boot\src\main\resources\application.properties) 
2. properties file does work when i move it to the root （\spring\boot\application.properties）
3. the build directory only has classes but no resources，and the application doesn't work with static resources.

I compare the maven project and the gradle project which both are generated originally by the intelliJ, the gradle project has a submodule where the problems may be, something relaed to the resource folder setting. I can't figure it out now。

![springboot_maven](https://user-images.githubusercontent.com/6346586/67734535-4be82e80-fa3c-11e9-9029-b4df233019d5.png)
![springboot_gradle](https://user-images.githubusercontent.com/6346586/67734539-4f7bb580-fa3c-11e9-8dcd-083e1586d798.png)
![springboot_gradle_main](https://user-images.githubusercontent.com/6346586/67734717-c1ec9580-fa3c-11e9-923d-e96faa8f9489.png)

**Comment by lonely917** [comment]
I use:
intelliJ 2019.2.1
springboot 2.2.0.RELEASE

**Comment by dsyer** [comment]
I'm not an IDEA user but isn't that expected? You have to ask IDEA to "build" the project before it changes the classpath.

**Comment by chbfiv** [comment]
Updated from 2018 to 2020 IntelliJ and it resolved it for me
