### ISSUE TITLE
[question] What is .adoc file extension, and what are tools to work with (e.g. Eclipse plugin)?

### ISSUE THREAD

**Issue by paulvi** [spring-guides/gs-spring-boot#8]
What is .adoc file extension, and what are tools to work with (e.g. Eclipse plugin)?

Is it AsciiDoc http://www.methods.co.nz/asciidoc/ ?

**Comment by kostukas** [comment]
Hallo adoc extension is an archive.
He's opening with 7zip application

**Comment by paulvi** [comment]
https://github.com/maxandersen/jbosstools-asciidoctor

**Comment by dsyer** [comment]
It's a plain text file. Just open it with a text editor.

**Comment by JRhoades22** [comment]
Asciidoclive worked really well for me:

https://asciidoclive.com/edit/scratch/1
